version: "3"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 app:APP
    volumes:
      - screen-images:/data/images
      - screen-db:/data/db
      - ./config/secret_client_secrets.json:/config/secret_client_secrets.json
    ports:
      - 8000:8000
    env_file:
      - ./config/config.env
volumes:
  screen-images:
  screen-db:
